spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}
  pulsar:
    client:
      service-url: ${PULSAR_URL}
  #    listener:
  #      schema-type=${PULSAR_SCHEMA_TYPE}
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: ${DATABASE_DDL_FORMAT}
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false


  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          introspection-uri: ${KEYCLOAK_INTROSPECTION_URI}
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
  application:
    name: ${IDENTITY_SERVICE_APPLICATION_NAME}

MAIL_HOST: ${EMAIL_HOST}
MAIL_PORT: ${EMAIL_PORT}
MAIL_USERNAME: ${EMAIL_USERNAME}
MAIL_PASSWORD: ${EMAIL_PASSWORD}
MAIL_SENDER: ${EMAIL_SENDER}

FRONTEND_URL: ${FRONTEND_BASE_URL:https://localhost:3000}


server:
  port: ${APPLICATION_PORT}

keycloak:
  server: ${KEYCLOAK_SERVER_URL}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}
  client-id: ${KEYCLOAK_CLIENT_ID}
  server-url: ${KEYCLOAK_SERVER_URL}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  master-realm: ${KEYCLOAK_MASTER_REALM}
  realm: ${KEYCLOAK_REALM}
  client: ${CLIENT}
  principal_attribute: preferred_username
  enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: '/documentation/identity/swagger-ui.html'
    filter: true
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    url: '/documentation/identity/v3/api-docs'
    config-url: '/documentation/identity/v3/api-docs/swagger-config'
  api-docs:
    path: '/documentation/identity/v3/api-docs'


example:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL}
    client-id: ${CLIENT_ID}
    master-client-id: ${ADMIN_CLIENT_ID}
    realm: ${KEYCLOAK_REALM}
    master-realm: ${KEYCLOAK_MASTER_REALM}
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
    client-secret: ${CLIENT_SECRET}



eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
qoreId:
  client-id: ${QORE_ID_CLIENT_ID}
  secret: ${QORE_ID_CLIENT_SECRET}
  url: ${QORE_ID_URL}
  nin-number: ${QORE_ID_TEST_NIN_NUMBER}
  bvn-number: ${QORE_ID_TEST_BVN_NUMBER}
  rc-number: ${QORE_ID_TEST_RC_NUMBER}


prembly:
  api-key: ${PREMBLY_API_KEY}
  app-id: ${PREMBLY_APP_ID}
  url: ${PREMBLY_URL}
  nin-number: ${PREMBLY_ID_TEST_NIN_NUMBER}
  bvn-number: ${PREMBLY_ID_TEST_BVN_NUMBER}
  cac-number: ${PREMBLY_ID_TEST_CAC_NUMBER}
