name: Deploy to Dev Environment

on:
  push:
    branches: 
      - workflows

env:
  REPO_URL: 357586184453.dkr.ecr.eu-west-1.amazonaws.com/identity-management-dev-backend
  ECR_REPOSITORY: identity-management-dev-backend
  ECR_REPOSITORY_SYSTEST: identity-management-systest
  AWS_REGION: eu-west-1
  CLUSTER: Gatekeeper
  SERVICE: identity-management
  SYSTEST_SERVICE: identity-management-systest
  DATABASE_URL: mongodb+srv://enumv2-db:PiD96zMcGQ51uglf@enumv2cluster.wzg2rjz.mongodb.net/
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  MASTER_REALM_CLIENT_SECRET: ${{ secrets.MASTER_REALM_CLIENT_SECRET }}
  ADMIN_CLIENT_SECRET: ${{ secrets.ADMIN_CLIENT_SECRET }}
  # Add all other environment variables here

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run deploy script
        run: |
          chmod +x .github/workflows/scripts/deploy.sh
          .github/workflows/scripts/deploy.sh
        env:
            S3_BUCKET: semicolon-build-reports
            PROJECT_NAME: karrabo/identity-management/maven-reports
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DATABASE_URL: ${{ env.DATABASE_URL }}
            DATABASE_NAME: ${{ env.DATABASE_NAME }}
            KEYCLOAK_INTROSPECTION_URI: ${{ secrets.KEYCLOAK_INTROSPECTION_URI }}
            KEYCLOAK_SERVER_URL: ${{ secrets.KEYCLOAK_SERVER_URL }}
            KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
            CLIENT_ID:  ${{ secrets.CLIENT_ID }}
            KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
            ADMIN_CLIENT_ID: ${{ secrets.ADMIN_CLIENT_ID }}
            KEYCLOAK_ADMIN_CLIENT_ID: ${{ secrets.KEYCLOAK_ADMIN_CLIENT_ID }}
            KEYCLOAK_MASTER_REALM: ${{ secrets.KEYCLOAK_MASTER_REALM }}
            KEYCLOAK_USERNAME: ${{ secrets.KEYCLOAK_USERNAME }}
            KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
            KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            EUREKA_URL: ${{ secrets.EUREKA_URL }}
            PROFILE: ${{ secrets.PROFILE }}
            IDENTITY_SERVICE_APPLICATION_NAME: ${{ secrets.IDENTITY_SERVICE_APPLICATION_NAME }}
            MASTER_REALM_CLIENT_SECRET: ${{ env.MASTER_REALM_CLIENT_SECRET }}
            ADMIN_CLIENT_SECRET: ${{ env.ADMIN_CLIENT_SECRET }}
            SECOND_CLIENT_SECRET: ${{ secrets.SECOND_CLIENT_SECRET}}
            PORT: ${{ secrets.PORT }}

            QORE_ID_CLIENT_ID: ${{ secrets.QORE_ID_CLIENT_ID }}
            QORE_ID_CLIENT_SECRET: ${{ secrets.QORE_ID_CLIENT_SECRET }}
            QORE_ID_URL: ${{ secrets.QORE_ID_URL }}
            QORE_ID_TEST_NIN_NUMBER: ${{ secrets.QORE_ID_TEST_NIN_NUMBER }}
            QORE_ID_TEST_BVN_NUMBER: ${{ secrets.QORE_ID_TEST_BVN_NUMBER }}
            QORE_ID_TEST_RC_NUMBER: ${{ secrets.QORE_ID_TEST_RC_NUMBER }}


            PREMBLY_API_KEY: ${{ secrets.PREMBLY_API_KEY }}
            PREMBLY_APP_ID: ${{ secrets.PREMBLY_APP_ID }}
            PREMBLY_URL: ${{ secrets.PREMBLY_URL }}
            PREMBLY_ID_TEST_NIN_NUMBER: ${{ secrets.PREMBLY_ID_TEST_NIN_NUMBER }}
            PREMBLY_ID_TEST_BVN_NUMBER: ${{ secrets.PREMBLY_ID_TEST_BVN_NUMBER }}
            PREMBLY_ID_TEST_CAC_NUMBER: ${{ secrets.PREMBLY_ID_TEST_CAC_NUMBER }}
            EUREKA_INSTANCE_HOSTNAME: ${{ secrets.EUREKA_INSTANCE_HOSTNAME }}

  run_tests:
    name: Run Automation Tests
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests script
        run: |
          chmod +x .github/workflows/scripts/run_tests.sh
          .github/workflows/scripts/run_tests.sh
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Pass all necessary environment variables

  build_and_analyze:
    name: Build and analyze
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build and analyze script
        run: |
          chmod +x .github/workflows/scripts/build_and_analyze.sh
          .github/workflows/scripts/build_and_analyze.sh
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DATABASE_URL: ${{ env.DATABASE_URL }}
            DATABASE_NAME: ${{ env.DATABASE_NAME }}
            KEYCLOAK_INTROSPECTION_URI: ${{ secrets.KEYCLOAK_INTROSPECTION_URI }}
            KEYCLOAK_SERVER_URL: ${{ secrets.KEYCLOAK_SERVER_URL }}
            KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
            CLIENT_ID:  ${{ secrets.CLIENT_ID }}
            KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
            ADMIN_CLIENT_ID: ${{ secrets.ADMIN_CLIENT_ID }}
            KEYCLOAK_ADMIN_CLIENT_ID: ${{ secrets.KEYCLOAK_ADMIN_CLIENT_ID }}
            KEYCLOAK_MASTER_REALM: ${{ secrets.KEYCLOAK_MASTER_REALM }}
            KEYCLOAK_USERNAME: ${{ secrets.KEYCLOAK_USERNAME }}
            KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
            KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            EUREKA_URL: ${{ secrets.EUREKA_URL }}
            PROFILE: ${{ secrets.PROFILE }}
            IDENTITY_SERVICE_APPLICATION_NAME: ${{ secrets.IDENTITY_SERVICE_APPLICATION_NAME }}
            MASTER_REALM_CLIENT_SECRET: ${{ env.MASTER_REALM_CLIENT_SECRET }}
            ADMIN_CLIENT_SECRET: ${{ env.ADMIN_CLIENT_SECRET }}
            SECOND_CLIENT_SECRET: ${{ secrets.SECOND_CLIENT_SECRET}}
            PORT: ${{ secrets.PORT }}

            QORE_ID_CLIENT_ID: ${{ secrets.QORE_ID_CLIENT_ID }}
            QORE_ID_CLIENT_SECRET: ${{ secrets.QORE_ID_CLIENT_SECRET }}
            QORE_ID_URL: ${{ secrets.QORE_ID_URL }}
            QORE_ID_TEST_NIN_NUMBER: ${{ secrets.QORE_ID_TEST_NIN_NUMBER }}
            QORE_ID_TEST_BVN_NUMBER: ${{ secrets.QORE_ID_TEST_BVN_NUMBER }}
            QORE_ID_TEST_RC_NUMBER: ${{ secrets.QORE_ID_TEST_RC_NUMBER }}


            PREMBLY_API_KEY: ${{ secrets.PREMBLY_API_KEY }}
            PREMBLY_APP_ID: ${{ secrets.PREMBLY_APP_ID }}
            PREMBLY_URL: ${{ secrets.PREMBLY_URL }}
            PREMBLY_ID_TEST_NIN_NUMBER: ${{ secrets.PREMBLY_ID_TEST_NIN_NUMBER }}
            PREMBLY_ID_TEST_BVN_NUMBER: ${{ secrets.PREMBLY_ID_TEST_BVN_NUMBER }}
            PREMBLY_ID_TEST_CAC_NUMBER: ${{ secrets.PREMBLY_ID_TEST_CAC_NUMBER }}
            EUREKA_INSTANCE_HOSTNAME: ${{ secrets.EUREKA_INSTANCE_HOSTNAME }}

